### PR TITLE
allow user to uses script outside git directory

### PR DESCRIPTION
**Pull request by lionncle**
- short development to allow user to use script phenogenius_cli.py out the git directory. 
- Another modification is apply to avoid error to get version from git tag : go to the package directory before to process command to get git tags. If the command not work the function return the python package version in place of "unknown"

### CODE REVIEW

**Comment by kyauy** [comment]
Thanks @lionncle !

**Comment by kyauy** [comment]
@lionncle I'll make a small update that should not change the behaviour for you.

I added the option to have "resource_dir" in click argument. By default, it will use your PR proposition. Otherwise if used in a container, the resources could be stored somewhere else and used in the script.

let me know if it's not okay for you.
```
@click.option(
    "--resource_dir",
    default=os.path.join(PACKAGE_DIR_PATH, "data", "resources"),
    help="(Optional) Path to resources directory, default = data/resources/",
)
```

**Comment by kyauy** [comment]
@lionncle I merge, let me know if it's not working!

**Comment by lionncle** [comment]
Hi, sorry for this late reply....
I haven't tested your development but I agree with you. I will be testing
it soon.

Le lun. 16 déc. 2024 à 17:02, Kévin Yauy ***@***.***> a
écrit :

**Pull request merged**
